import type { Mix } from '../../types'

export const demoMixes: Record<string, Mix> = {
  mix_bikes: {
    mix_id: 'mix_bikes',
    query: 'велосипеды',
    total_duration_sec: 340,
    stages: [
      {
        title: 'Как выбрать класс велосипеда',
        description: 'Гайд для новичков: классы MTB (XC, трейл, эндуро), статистика ошибок 4000 покупателей и почему «хардтейл XC — самый универсальный».',
        scenes: [
          {
            video_id: 'bike_dont_buy',
            scene_index: 0,
            start_sec: 0,
            end_sec: 90,
            summary: 'Интро и постановка проблемы: как не ошибиться с первым велосипедом',
            speaker: 'SPEAKER_00',
            text: 'Современный мир велосипедов огромен: десятки классов, сотни брендов. Очень легко ошибиться с классом, ценой или ростовкой.',
            monetization_types: ['clip_candidate', 'ad_slot'],
          },
          {
            video_id: 'bike_dont_buy',
            scene_index: 3,
            start_sec: 303,
            end_sec: 430,
            summary: 'Ошибка класса: 48% ошиблись; хардтейл XC — 44%. В кадре Aspect AMP DC Elite за 127 000 ₽',
            speaker: 'SPEAKER_00',
            text: 'Ошибка №1 — класс. Самая частая — хардтейл XC. Универсальный горный велосипед с вилкой до 120 мм.',
            monetization_types: ['ecom_item', 'ecom_item', 'ad_slot'],
          },
        ],
      },
      {
        title: 'ТОП моделей апреля 2025',
        description: 'Подборка лучших велосипедов от 30 до 160 тысяч: городской универсал, гравий и фитнес-МТВ.',
        scenes: [
          {
            video_id: 'bike_top_april',
            scene_index: 1,
            start_sec: 22,
            end_sec: 66,
            summary: 'Hagen HG10 — универсальный дорожный/гравий за 91 000 ₽, карбоновая вилка, вес 11 кг',
            speaker: 'SPEAKER_00',
            text: 'Hagen HG10 — идеальная пушка для комбинированной езды по городу за 91 000 ₽.',
            monetization_types: ['ecom_item', 'ecom_item'],
          },
          {
            video_id: 'bike_top_april',
            scene_index: 2,
            start_sec: 92,
            end_sec: 160,
            summary: 'Welt G10 и Aspect Allroad Elite — гравий 2x10 и 1x11 с Shimano GRX; цены 150 и 160 000 ₽',
            speaker: 'SPEAKER_00',
            text: 'Welt G10 — 150 000 ₽, трансмиссия 2x10, GRX-400. Aspect Allroad Elite — 1x11, GRX-800, 160 000 ₽.',
            monetization_types: ['ecom_item', 'ecom_item'],
          },
          {
            video_id: 'bike_top_april',
            scene_index: 4,
            start_sec: 215,
            end_sec: 265,
            summary: 'Rush Hour — фитнес-МТВ за 30 000 ₽, конусный стакан, 1x9 Shimano Acera',
            speaker: 'SPEAKER_00',
            text: 'Rush Hour — гроза бюджетного сегмента. Классная рама с внутренней проводкой за 30 000 ₽.',
            monetization_types: ['ecom_item'],
          },
        ],
      },
      {
        title: 'Чек-лист покупки 80 000₽',
        description: 'Как не купить хлам: рама, вилка Suntour/китайская, трансмиссия Shimano Cues 9ск, тормоза MT200.',
        scenes: [
          {
            video_id: 'bike_mtb_80k',
            scene_index: 5,
            start_sec: 591,
            end_sec: 660,
            summary: 'Колёса и покрышки: размер 27.5/29, обода 21-23 мм, покрышки 2.25+ Schwalbe/Maxxis/Kenda',
            speaker: 'SPEAKER_00',
            text: 'Покрышки хорошие — Schwalbe/Maxxis; норма — Kenda; Chaoyang — ниже нормы для выбора.',
            monetization_types: ['ecom_item'],
          },
          {
            video_id: 'bike_mtb_80k',
            scene_index: 7,
            start_sec: 724,
            end_sec: 770,
            summary: 'Тормоза: гидравлика MT200 — хорошо, Tektro M275 — норм; механика — красный флаг в этом бюджете',
            speaker: 'SPEAKER_00',
            text: 'Тормоза должны быть гидравлические. Shimano MT200 — хорошо, Tektro M275 — нормально.',
            monetization_types: ['ecom_item'],
          },
          {
            video_id: 'bike_mtb_80k',
            scene_index: 9,
            start_sec: 835,
            end_sec: 866,
            summary: 'Итог: 80 000 ₽ дают компромиссный, но не «хлам» байк; приоритет — ваша задача',
            speaker: 'SPEAKER_00',
            text: 'За 80 000 откровенно плохой велосипед не купить. Выбор должен ориентироваться на задачу.',
            monetization_types: ['clip_candidate'],
          },
        ],
      },
    ],
  },
  mix_headphones: {
    mix_id: 'mix_headphones',
    query: 'как выбрать наушники',
    total_duration_sec: 754,
    stages: [
      {
        title: 'Типы наушников',
        description: 'Обзор основных типов наушников: вкладыши, накладные, полноразмерные. Поможем понять, какой тип подходит для разных задач.',
        scenes: [
          {
            video_id: 'tech_review',
            scene_index: 1,
            start_sec: 12,
            end_sec: 45,
            summary: 'Спикер рассказывает о типах наушников и их особенностях',
            speaker: 'SPEAKER_00',
            text: 'Наушники делятся на вкладыши, накладные и полноразмерные. У каждого типа свои плюсы и минусы.',
            monetization_types: ['ad_slot'],
          },
          {
            video_id: 'tech_review',
            scene_index: 2,
            start_sec: 45,
            end_sec: 82,
            summary: 'Сравнение вкладышей и накладных наушников по качеству звука',
            speaker: 'SPEAKER_00',
            text: 'Вкладыши компактные, но уступают в звуке накладным. Накладные — золотая середина.',
            monetization_types: ['ad_slot', 'ecom_item'],
          },
          {
            video_id: 'tech_review',
            scene_index: 3,
            start_sec: 82,
            end_sec: 108,
            summary: 'Полноразмерные наушники для домашнего прослушивания',
            speaker: 'SPEAKER_00',
            text: 'Полноразмерные наушники дают najlepszy звук, но менее портативны.',
            monetization_types: ['ecom_item'],
          },
        ],
      },
      {
        title: 'Характеристики звука',
        description: 'Разбираем ключевые характеристики: частотный диапазон, импеданс, чувствительность. Что реально важно при выборе.',
        scenes: [
          {
            video_id: 'tech_review',
            scene_index: 4,
            start_sec: 108,
            end_sec: 145,
            summary: 'Частотный диапазон и импеданс: что нужно знать',
            speaker: 'SPEAKER_00',
            text: 'Частотный диапазон 20Гц-20кГц — стандарт. Импеданс влияет на громкость.',
            monetization_types: ['ad_slot'],
          },
          {
            video_id: 'tech_review',
            scene_index: 5,
            start_sec: 145,
            end_sec: 185,
            summary: 'Чувствительность и мощность: как громко будут играть наушники',
            speaker: 'SPEAKER_00',
            text: 'Чувствительность измеряется в дБ. Чем выше — тем громче наушники при той же мощности.',
            monetization_types: ['ad_slot', 'ecom_item'],
          },
        ],
      },
      {
        title: 'Сравнение моделей',
        description: 'Сравниваем популярные модели Sony, Audio-Technica и Sennheiser в разных ценовых категориях.',
        scenes: [
          {
            video_id: 'tech_review',
            scene_index: 8,
            start_sec: 210,
            end_sec: 250,
            summary: 'Sony WH-1000XM5: флагман с лучшим шумоподавлением',
            speaker: 'SPEAKER_00',
            text: 'Sony XM5 — лучшие в шумоподавлении, отличный звук, но дорогие.',
            monetization_types: ['ecom_item', 'ad_slot'],
          },
          {
            video_id: 'tech_review',
            scene_index: 9,
            start_sec: 250,
            end_sec: 274,
            summary: 'Audio-Technica ATH-M50x: легендарные студийные мониторы',
            speaker: 'SPEAKER_00',
            text: 'ATH-M50x — стандарт студийного мониторинга, нейтральный звук.',
            monetization_types: ['ecom_item'],
          },
        ],
      },
      {
        title: 'Вердикт и рекомендации',
        description: 'Итоговые рекомендации по выбору наушников под разные задачи и бюджет.',
        scenes: [
          {
            video_id: 'tech_review',
            scene_index: 13,
            start_sec: 350,
            end_sec: 380,
            summary: 'Итоговые рекомендации по выбору наушников',
            speaker: 'SPEAKER_00',
            text: 'Для дома — полноразмерные, для улицы — накладные с шумоподавлением. Бюджет — от 5000 до 30000 рублей.',
            monetization_types: ['ad_slot', 'clip_candidate'],
          },
        ],
      },
    ],
  },
}
